name: Build DB image
on:
  push:
    branches:
      - main
      - develop
      # - feature*
      
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4